### ISSUE TITLE
Documentation lists python-fuse

### ISSUE THREAD

**Issue by nitecon** [denismo/DynamoFS#48]
Documentation currently lists the use of python-fuse as requirement but the package python-fuse is not available under pip (RH6 based) Is this something that is specific to an OS distro?  Documentation references yum, so the assumption is made that it is available for redhat based OS's but the libraries do not exist.  Also what versions of python is required to run the software?

**Comment by denismo** [comment]
Apologies, the documentation is misleading. I'm using  terencehonles/fusepy
Python 2.6 and later (not tested with 3 but should work).

|   |
|   |  |   |   |   |   |   |
| terencehonles/fusepyfusepy - Simple ctypes bindings for FUSE |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |

**Comment by nitecon** [comment]
Forgot to get back to this and close the issue, thanks for the response it solved my issue.
